/* The only JavaScript on the site: the dark-mode toggle.
   Pages are real HTML generated by Jekyll, so navigation, routing and content
   all work with JavaScript disabled — this just remembers a colour preference. */

(function () {
  'use strict';

  var ICON = {
    moon: '<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M12 3a6 6 0 0 0 9 9 9 9 0 1 1-9-9Z"></path></svg>',
    sun: '<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><circle cx="12" cy="12" r="4"></circle><path d="M12 2v2"></path><path d="M12 20v2"></path><path d="m4.93 4.93 1.41 1.41"></path><path d="m17.66 17.66 1.41 1.41"></path><path d="M2 12h2"></path><path d="M20 12h2"></path><path d="m6.34 17.66-1.41 1.41"></path><path d="m19.07 4.93-1.41 1.41"></path></svg>',
  };

  function isDark() {
    try {
      return localStorage.getItem('pf-theme') === 'dark';
    } catch (e) {
      return false; // private mode — fall back to the default
    }
  }

  function apply() {
    var dark = isDark();
    document.body.dataset.pfTheme = dark ? 'dark' : 'light';
    var btn = document.getElementById('theme-toggle');
    if (!btn) return;
    btn.innerHTML = dark ? ICON.sun : ICON.moon;
    btn.setAttribute('aria-label', dark ? 'Switch to light mode' : 'Switch to dark mode');
  }

  document.addEventListener('DOMContentLoaded', function () {
    apply();

    var btn = document.getElementById('theme-toggle');
    if (!btn) return;

    btn.addEventListener('click', function () {
      try {
        localStorage.setItem('pf-theme', isDark() ? 'light' : 'dark');
      } catch (e) { /* preference just won't persist */ }
      apply();
    });
  });
})();
